item { 
	name:'3-accident'
	id:1
}
item { 
	name:'5-man'
	id:2
}
item { 
	name:'book'
	id:3
}
item { 
	name:'break-down'
	id:4
}
item { 
	name:'car'
	id:5
}
item { 
	name:'ix-1p'
	id:6
}
item { 
	name:'ix-3p_j'
	id:7
}
item { 
	name:'ix-loc_j'
	id:8
}
item { 
	name:'know-that'
	id:9
}
item { 
	name:'monday'
	id:10
}
item { 
	name:'name'
	id:11
}
item { 
	name:'not-yet+'
	id:12
}
item { 
	name:'park'
	id:13
}
item { 
	name:'part_indef'
	id:14
}
item { 
	name:'phone'
	id:15
}
item { 
	name:'poss-1p'
	id:16
}
item { 
	name:'show'
	id:17
}
item { 
	name:'something-one'
	id:18
}
item { 
	name:'student'
	id:19
}
item { 
	name:'test'
	id:20
}
item { 
	name:'who'
	id:21
}
